server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: techstore-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Cấu hình tài liệu Swagger OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

# Cấu hình JWT Security
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}      # 30 phút (ms)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:2592000000} # 30 ngày (ms)
